module Spree
  module GoToMeeting
    CLIENT_ID = 'YOUR_CLIENT_ID'
    CONSUMER_SECRET ='YOUR_CONSUMER_SECRET'
    ACCESS_TOKEN = 'YOUR_ACCESS_TOKEN'
    ORGANIZER_KEY = 'YOUR_ORGANIZER_KEY'
  end
end
